services:
  postgres-db-p2-dev:
    image: postgres
    container_name: postgres-db-p2-dev
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: