server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: relatorios-api
  config:
    activate:
      on-profile: "dev"
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres-db
    username: root
    password: root123
