server:
  port: ${SERVER_PORT:8080}

feign:
  config:
    default:
      loggerLevel: full
  client:
    viacep:
      url: "https://viacep.com.br/ws"
      timeout: 2000
      loggerLevel: full

spring:
  application:
    name: agendaservico
  profiles:
    active: "local"
    default: "local"
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bancodb
    username: sa
    password: 1234
  h2:
    console:
      enabled: true