server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: agendaservico
  profiles:
    active: "local"
    default: "local"
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bancodb
    username: sa
    password: 1234
  h2:
    console:
      enabled: true